version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: asadah_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./asadah-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/asadah_db
    depends_on:
      - db

  frontend:
    build: ./asadah-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
