version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ersah
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ersah_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://ersah:secret@db:5432/ersah_db
      SECRET_KEY: supersecretkey
      OPENAI_API_KEY: ""
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      VITE_API_URL: http://localhost:8000

volumes:
  pgdata: